# Objective :

Our objective is to analyze the overall bias crimes that occured in NYC that had an Anti- Asian motive. Hate crimes are offenses that are motivated in whole or substantial part by a person's a group, or a place's identification with a particular race, religion, ethnicity, gender, age, disability, ancestry, national origin or sexual orientation.

# What Is A Hate Crime ?


# How Many Hate Crimes Occur Per Year ?

# Our Data:

The data is organized by the report sightings that are 
found per each precicnt. Each is selected by bias category, 
and bias type with the offense description of what they face. Ranging from
the first date to most recent date, and analyzed from quarterly reports 
that are passed to the NYPD. All with a specific offense description
and the number of arrests that occured within that day.

In [1]:
import numpy as np 
import pandas as pd

In [5]:
df = pd.read_csv("hate-crime-arrests-by-motivation-annual-2020.csv")
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NYC Hate Crime Report,NaN,NaN,NaN,NaN,NaN
1,Arrest Statistics involving Hate Crime Incidents,NaN,NaN,NaN,NaN,NaN
2,"by Arrestee Gender, Race, Age and Bias Motivation",NaN,NaN,NaN,NaN,NaN
3,CY2020,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
94,89,120,FEMALE,WHITE HISPANIC,70,ANTI-ASIAN
95,90,120,FEMALE,WHITE HISPANIC,70,ANTI-BLACK
96,91,120,FEMALE,WHITE HISPANIC,70,ANTI-MALE HOMOSEXUAL(GAY)
97,92,120,FEMALE,WHITE HISPANIC,70,ANTI-WHITE
98,93,120,FEMALE,WHITE HISPANIC,70,ANTI-WHITE

## The first couple rows are actually supposed to be calling the column names therefore we can use a delimiter to fix this.

In [6]:
df[5:]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
5,Number,Precinct,Gender,Race,Age,Bias-Motivation
6,1,005,MALE,BLACK HISPANIC,38,ANTI-ASIAN
7,2,005,MALE,WHITE,32,ANTI-JEWISH
8,3,006,MALE,BLACK,38,ANTI-ASIAN
9,4,006,MALE,BLACK,37,ANTI-MALE HOMOSEXUAL(GAY)
...,...,...,...,...,...,...
94,89,120,FEMALE,WHITE HISPANIC,70,ANTI-ASIAN
95,90,120,FEMALE,WHITE HISPANIC,70,ANTI-BLACK
96,91,120,FEMALE,WHITE HISPANIC,70,ANTI-MALE HOMOSEXUAL(GAY)
97,92,120,FEMALE,WHITE HISPANIC,70,ANTI-WHITE
98,93,120,FEMALE,WHITE HISPANIC,70,ANTI-WHITE

## So our column is actually supposed to be row 5, and the data is supposed to be organized from column 6 down